### ISSUE TITLE
FR: Support for templaterjs

### ISSUE THREAD

**Issue by chrisgrieser** [1C0D/Obsidian-Contextual-Comments#4]
templater scripts are not wrapped in code blocks like dataviewjs, but having support for them would nonetheless be very useful.

**Comment by 1C0D** [comment]
I have zero exp around templater. I searched a little bit but found nothing around comments.
can you show me an example?

**Comment by chrisgrieser** [comment]
So templater scripts are basically javascript, enclosed in `<%*` `%>` ([reference in the docs](https://silentvoid13.github.io/Templater/user-functions/script-user-functions.html)):

```js
<%*
// turn off spellcheck
this.app.vault.setConfig("spellcheck", false);
%>
```

There are some minor edge cases where you can use slightly different syntax [for white space control](https://silentvoid13.github.io/Templater/commands/whitespace-control.html): `<%_`, `<%-`, `_%>`, `-%>`. (The Syntax for Dynamic commands you can disregard, since those are deprecated, even though the docs do not say so yet)

---

Inside those markers, it's pretty much javascript, so `//` for comments would be great. If you have templater installed, you also also get syntax highlighting in edit mode for those, meaning you do have classes in the DOM to work with. I think it should be only only `.templater-inline` and `.templater-command-bg`

![CleanShot 2023-02-23 at 08 33 30](https://user-images.githubusercontent.com/73286100/220844645-e1d3176f-5e5d-48f1-bfbb-233ab4d55594.png)

**Comment by 1C0D** [comment]
thks for this precise answer!
Done.

**Comment by chrisgrieser** [comment]
thanks you 🥳
