### ISSUE TITLE
Support for some languages removed?

### ISSUE THREAD

**Issue by chrisgrieser** [1C0D/Obsidian-Contextual-Comments#5]
Hi, I just noticed that the plugin seems to have dropped support for a few languages that I previously added in a PR? 

Looks like here in this commit: https://github.com/1C0D/Obsidian-Contextual-Comments/commit/21fcf3319481e3f8c947343a709820074dbb19d5#diff-22d58f67f2774d0f69001c28f361388aae8e6901d9e216461144c7249f68c581L19-L31

Was this maybe an accident?

**Comment by 1C0D** [comment]
thks for reporting this. I guess I pushed code from my computer without having pulled it before. Or did I do it manually, having an error with my push? Possible, I was not too at ease with github at first.

**Comment by chrisgrieser** [comment]
thanks, the latest commit fixed it
